# Generated by Django 5.2.1 on 2025-08-29 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=' شماره نوع مصرف')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان نوع مصرف')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=' شماره دستگاه')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دستگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره گروه')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان گروه')),
            ],
            options={
                'verbose_name': 'گروه کالا',
                'verbose_name_plural': 'گروه کالاها',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره واحد')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان واحد')),
            ],
            options={
                'verbose_name': 'واحد کالا',
                'verbose_name_plural': 'واحدهای کالا',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد انبار')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره انبار')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.device', verbose_name='عنوان دستگاه')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.productgroup', verbose_name='گروه کالا')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.unit', verbose_name='واحد کالا')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
