# Generated by Django 5.2.1 on 2025-09-12 16:49

import HesabdariApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره خریدار')),
                ('name', models.CharField(max_length=255, verbose_name='نام مرکز / نام شخص (حقیقی/حقوقی)')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس مرکز / شماره تماس شخص در ارتباط')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=' شماره نوع مصرف')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان نوع مصرف')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=' شماره دستگاه')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دستگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(blank=True, max_length=5, unique=True, verbose_name='کد پرسنلی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره گروه')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان گروه')),
            ],
            options={
                'verbose_name': 'گروه کالا',
                'verbose_name_plural': 'گروه کالاها',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره تامین کننده')),
                ('name', models.CharField(max_length=255, verbose_name='نام تامین\u200cکننده')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر فروشگاه')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره واحد')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان واحد')),
            ],
            options={
                'verbose_name': 'واحد کالا',
                'verbose_name_plural': 'واحدهای کالا',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره انبار')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='buy_invoice/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.personnel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.seller')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HesabdariApp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('national_card', 'کارت ملی'), ('birth_certificate', 'شناسنامه / کارت دانشجویی'), ('vehicle_card', 'کارت خودرو')], max_length=50)),
                ('file', models.FileField(upload_to=HesabdariApp.models.personnel_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HesabdariApp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد اختصاصی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.device', verbose_name='عنوان دستگاه')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.productgroup', verbose_name='گروه کالا')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='sell_invoice/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.seller')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HesabdariApp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SellInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.product')),
                ('sell_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HesabdariApp.sellinvoice')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.unit')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='BuyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('buy_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HesabdariApp.buyinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HesabdariApp.unit')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('product_code', models.CharField(max_length=100, verbose_name='کد اختصاصی')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='شماره فاکتور')),
                ('serial_number', models.CharField(max_length=150, verbose_name='سریال کالا')),
                ('sell_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_out_items', to='HesabdariApp.sellinvoiceitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.warehouse', verbose_name='خروج از انبار')),
            ],
            options={
                'verbose_name': 'کالای خروجی از انبار',
                'verbose_name_plural': 'کالاهای خروجی از انبار',
                'indexes': [models.Index(fields=['product_code', 'invoice_number'], name='HesabdariAp_product_4e4f22_idx'), models.Index(fields=['serial_number'], name='HesabdariAp_serial__a27123_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('product_code', models.CharField(max_length=100, verbose_name='کد اختصاصی')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='شماره فاکتور')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='سریال کالا')),
                ('buy_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='HesabdariApp.buyinvoiceitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.warehouse', verbose_name='انبار مقصد')),
            ],
            options={
                'verbose_name': 'کالای ورودی به انبار',
                'verbose_name_plural': 'کالاهای ورودی به انبار',
                'indexes': [models.Index(fields=['product_code', 'invoice_number'], name='HesabdariAp_product_79084d_idx'), models.Index(fields=['serial_number'], name='HesabdariAp_serial__37384b_idx')],
            },
        ),
    ]
