# Generated by Django 5.2.1 on 2025-08-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان نوع مصرف')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان گروه')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان واحد')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد انبار')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='حداقل تعداد')),
                ('max_quantity', models.PositiveIntegerField(default=0, verbose_name='حداکثر تعداد')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت فروش')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف فروش')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات')),
                ('duty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد عوارض')),
                ('final_tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='مالیات بر مصرف نهایی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.productgroup', verbose_name='گروه کالا')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.unit', verbose_name='واحد کالا')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HesabdariApp.warehouse', verbose_name='مکان کالا')),
            ],
        ),
    ]
