# Generated by Django 5.2.1 on 2025-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=50, unique=True, verbose_name='کد پرسنلی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شناسنامه')),
                ('national_card_file', models.FileField(blank=True, null=True, upload_to='personnel/national_cards/', verbose_name='کارت ملی')),
                ('birth_certificate_file', models.FileField(blank=True, null=True, upload_to='personnel/birth_certificates/', verbose_name='شناسنامه / کارت دانشجویی / آخرین مدرک')),
                ('vehicle_card_file', models.FileField(blank=True, null=True, upload_to='personnel/vehicle_cards/', verbose_name='کارت خودرو (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
