# Generated by Django 5.2.1 on 2025-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='serial',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
