# Generated by Django 5.2.1 on 2025-09-04 23:48

import HesabdariApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='birth_certificate_file',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='national_card_file',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='vehicle_card_file',
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('national_card', 'کارت ملی'), ('birth_certificate', 'شناسنامه / کارت دانشجویی'), ('vehicle_card', 'کارت خودرو')], max_length=50)),
                ('file', models.FileField(upload_to=HesabdariApp.models.personnel_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HesabdariApp.personnel')),
            ],
        ),
    ]
