# Generated by Django 5.2.1 on 2025-08-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0002_personnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={},
        ),
        migrations.AddField(
            model_name='personnel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_code',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='کد پرسنلی'),
        ),
    ]
