# Generated by Django 5.2.1 on 2025-08-26 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0002_productgroup_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='serial',
        ),
        migrations.AlterField(
            model_name='consumptiontype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='کد انبار'),
        ),
    ]
