# Generated by Django 5.2.1 on 2025-09-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0002_remove_personnel_birth_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
