# Generated by Django 5.2.1 on 2025-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0003_alter_buyer_created_at_alter_buyer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
