# Generated by Django 5.2.1 on 2025-08-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0003_alter_personnel_options_personnel_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مرکز / نام شخص (حقیقی/حقوقی)')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس مرکز / شماره تماس شخص در ارتباط')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تامین\u200cکننده')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر فروشگاه')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
