# Generated by Django 5.2.1 on 2025-08-27 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0003_remove_productgroup_serial_alter_consumptiontype_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'گروه کالا', 'verbose_name_plural': 'گروه کالاها'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'واحد کالا', 'verbose_name_plural': 'واحدهای کالا'},
        ),
        migrations.AddField(
            model_name='consumptiontype',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شماره نوع مصرف'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره گروه'),
        ),
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره واحد'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد انبار'),
        ),
    ]
