# Generated by Django 5.2.1 on 2025-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0004_alter_productgroup_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiontype',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=' شماره نوع مصرف'),
        ),
    ]
