# Generated by Django 5.2.1 on 2025-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0004_alter_seller_created_at_alter_seller_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
