# Generated by Django 5.2.1 on 2025-08-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0004_buyer_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره خریدار'),
        ),
        migrations.AddField(
            model_name='seller',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره فروشنده'),
        ),
    ]
