# Generated by Django 5.2.1 on 2025-09-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0005_buyer_number_seller_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد اختصاصی'),
        ),
        migrations.CreateModel(
            name='BuyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='buy_invoice/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.personnel')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HesabdariApp.warehouse')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='BuyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد اختصاصی')),
                ('economic_code', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('buy_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HesabdariApp.buyinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.product')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
