# Generated by Django 5.2.1 on 2025-08-27 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0005_alter_consumptiontype_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=' شماره دستگاه')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دستگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.device', verbose_name='عنوان دستگاه'),
            preserve_default=False,
        ),
    ]
