# Generated by Django 5.2.1 on 2025-09-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0006_remove_product_model_product_product_code_buyinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyinvoiceitem',
            name='economic_code',
        ),
    ]
