# Generated by Django 5.2.1 on 2025-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0006_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='buyinvoice',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='buyinvoice',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='sellinvoice',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
