# Generated by Django 5.2.1 on 2025-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0007_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
