# Generated by Django 5.2.1 on 2025-09-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0007_remove_buyinvoiceitem_economic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='buyinvoiceitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره تامین کننده'),
        ),
    ]
