# Generated by Django 5.2.1 on 2025-09-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0007_remove_product_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinvoiceitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HesabdariApp.unit'),
        ),
        migrations.AddField(
            model_name='sellinvoiceitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.unit'),
        ),
    ]
