# Generated by Django 5.2.1 on 2025-09-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0008_buyinvoiceitem_unit_sellinvoiceitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('product_code', models.CharField(max_length=100, verbose_name='کد اختصاصی')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='شماره فاکتور')),
                ('serial_number', models.CharField(max_length=150, unique=True, verbose_name='سریال کالا')),
                ('buy_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='HesabdariApp.buyinvoiceitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HesabdariApp.warehouse', verbose_name='انبار مقصد')),
            ],
            options={
                'verbose_name': 'کالای ورودی به انبار',
                'verbose_name_plural': 'کالاهای ورودی به انبار',
                'indexes': [models.Index(fields=['product_code', 'invoice_number'], name='HesabdariAp_product_79084d_idx'), models.Index(fields=['serial_number'], name='HesabdariAp_serial__37384b_idx')],
            },
        ),
    ]
