# Generated by Django 5.2.1 on 2025-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HesabdariApp', '0008_alter_product_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره کالا'),
        ),
    ]
